### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by tarciosaraiva** [reid/pact#7]
Hey there
I was wondering if we could have a quick discussion about the package name.

I'm a developer here in Australia and we have a project named Pact (http://docs.pact.io/). The project has been evolving and now we are ready to release a Javascript version.

I noticed that this package hasn't been updated in a while and I'm wondering if it still relevant / maintained?

I would love to have a package named `pact` in NPM that actually reflect the above and not Vows.

Looking forward to your reply :+1:

Cheers 🍻

**Comment by reid** [comment]
Sure thing, let me read up on how to transfer.

**Comment by tarciosaraiva** [comment]
That's awesome, thanks mate! 👍

**Comment by reid** [comment]
Done! Wishing you well with your project! 🍻 

```
$ npm owner add tarcio pact
+ tarcio (pact)
```
